
# SITE CONFIGURATION
title: Rapid XAML
author: Matt Lacey
description: Tools to accelerate XAML app development.
url: "https://rapidxaml.dev/"

tagline: >
  Tools to accelerate XAML app development.<br />
  Don't waste time writing XAML.
encoding: UTF-8

#hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg
hero_img: posts/toolkit.png

twitter_username: mrlacey
github_username:  mrlacey/rapidxamldev

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
